name: yeohaeng_ttukttak_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  flutter_map: ^8.1.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.5
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Noto Sans
    fonts:
    - asset: fonts/NotoSansKR-Black.ttf
      weight: 900
    - asset: fonts/NotoSansKR-ExtraBold.ttf
      weight: 800
    - asset: fonts/NotoSansKR-Bold.ttf
      weight: 700
    - asset: fonts/NotoSansKR-SemiBold.ttf
      weight: 600
    - asset: fonts/NotoSansKR-Medium.ttf
      weight: 500
    - asset: fonts/NotoSansKR-Regular.ttf
      weight: 400
    - asset: fonts/NotoSansKR-Light.ttf
      weight: 300
    - asset: fonts/NotoSansKR-ExtraLight.ttf
      weight: 200
    - asset: fonts/NotoSansKR-Thin.ttf
      weight: 100