name: Deploy Client to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.30.0-0.1.pre
      
      - name: Get Dependencies
        run: flutter pub get
      
      - name: Build Flutter Web
        run: flutter build web --wasm --release

      - name: Publish to remote server
        working-directory: build
        run: rsync -r web ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}:/home/yeohaeng_ttukttak
