name: Deploy Client to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install rsync
        run: sudo apt update && sudo apt -yq install rsync openssh-client

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          architecture: x64
          flutter-version: 3.30.0-0.1.pre
          cache: true
      
      - name: Get Dependencies
        run: flutter pub get
      
      - name: Build Flutter Web
        run: flutter build web --wasm --release

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: GitHub SSH known hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          sudo ssh-keyscan ${{ secrets.REMOTE_SERVER_HOST }} > ~/.ssh/known_hosts
          

      - name: Publish to remote server
        working-directory: build
        run: rsync -r web ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}:/home/yeohaeng_ttukttak
