name: Deploy Client to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          ssh-keyscan ${{ secrets.REMOTE_SERVER_HOST }} > ~/.ssh/known_hosts

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          architecture: x64
          flutter-version: 3.30.0-0.1.pre
          cache: true
      
      - name: Get Dependencies
        run: flutter pub get
      
      - name: Build Flutter Web
        run: flutter build web --wasm --release

      - name: Publish to remote server
        working-directory: build
        run: rsync -r web ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}:/home/yeohaeng_ttukttak
